[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mathly"
version = "0.1.2"
description = "A simple, LLM-friendly math rendering library for Algebra and Calculus."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Muhammad Zohaib Saeed" }
]
dependencies = [
    "matplotlib>=3.5.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]
